# App config
STEP_INTERVAL = 0.001
SATISFACTORY_THRESHOLD = 160
COMMS_RANGE = 32

# Map config
MAP_SIZE = (192, 192)
MAP_RES = (8, 8)
PERLIN_OCTAVES = 3

# Robots config
ROBOTS_COUNT = 8
ROBOTS_DEPLOY_POINT_X = MAP_SIZE[0] // 2
ROBOTS_DEPLOY_POINT_Y = MAP_SIZE[1] // 2
ROBOTS_COLOR_SEARCHING = "b" # blue
ROBOTS_COLOR_DONE = "g" # green
ROBOTS_SIZE = 20